---
title: "R Package Risk Metrics"
author: ""
date: "`r Sys.Date()`"
output:
  github_document
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<style>
    body .main-container {
        max-width: 2000px;
    }
</style>

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, echo = FALSE, message = FALSE}
library(riskmetric)
library(dplyr)
# rmarkdown::render("riskmetric.Rmd",  output_dir = "../reports/")
```

By following [https://preview--condescending-lewin-a2fc51.netlify.com/packages/](R validation hub) validation information, riskmetric R package is created for proof of concept. All of content in this R package is draft only. 

* `data/riskmetric.Rd` contain the existing risk metrics generated by `riskmetric:::get_riskmetric` function. 

# Function Definition
```{r}
riskmetric:::get_riskmetric
```

# Load Data
```{r}
riskmetric <- readRDS("../data/riskmetric.Rd")
```

# Explore the data
```{r, eval = FALSE, echo = FALSE}
# Only work in development mode
View(riskmetric)
```

```{r}
# Dependncy variable is a listing in current riskmetric format. And not be able to display properly. 
riskmetric %>% dplyr::select(-dependency)
```

