#' Import metrics
#'
#' @param file (`character`) Path to the file to import.
#'
#' @returns The object in the same format and class as generated by riskmetric.
#' @export
#' @seealso pkg_metric_export()
pkg_metric_import <- function(file) {
  if (!file.exists(file)) {
    stop("Please provide a path to a file.")
  }
  dcf <- read.dcf(file)
  dcf <- as.data.frame(dcf)
  dcf
}
